server:
  port: 6060
logging:
  config: 'classpath:logback.xml'
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.215.223:3306/slice?setUnicode=true&characterEncoding=utf8
    username: client
    password: Abc123456