package com.hongtu.slice.db.entity;

public class TbCatalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.synopsis
     *
     * @mbggenerated
     */
    private String synopsis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.visible
     *
     * @mbggenerated
     */
    private Byte visible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.sortid
     *
     * @mbggenerated
     */
    private Integer sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.chapsort
     *
     * @mbggenerated
     */
    private Integer chapsort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.nodesort
     *
     * @mbggenerated
     */
    private Integer nodesort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.sliceflag
     *
     * @mbggenerated
     */
    private Integer sliceflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_catalog.idcode
     *
     * @mbggenerated
     */
    private String idcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.id
     *
     * @return the value of tb_catalog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.id
     *
     * @param id the value for tb_catalog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.name
     *
     * @return the value of tb_catalog.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.name
     *
     * @param name the value for tb_catalog.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.pid
     *
     * @return the value of tb_catalog.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.pid
     *
     * @param pid the value for tb_catalog.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.synopsis
     *
     * @return the value of tb_catalog.synopsis
     *
     * @mbggenerated
     */
    public String getSynopsis() {
        return synopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.synopsis
     *
     * @param synopsis the value for tb_catalog.synopsis
     *
     * @mbggenerated
     */
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis == null ? null : synopsis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.visible
     *
     * @return the value of tb_catalog.visible
     *
     * @mbggenerated
     */
    public Byte getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.visible
     *
     * @param visible the value for tb_catalog.visible
     *
     * @mbggenerated
     */
    public void setVisible(Byte visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.sortid
     *
     * @return the value of tb_catalog.sortid
     *
     * @mbggenerated
     */
    public Integer getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.sortid
     *
     * @param sortid the value for tb_catalog.sortid
     *
     * @mbggenerated
     */
    public void setSortid(Integer sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.category
     *
     * @return the value of tb_catalog.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.category
     *
     * @param category the value for tb_catalog.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.chapsort
     *
     * @return the value of tb_catalog.chapsort
     *
     * @mbggenerated
     */
    public Integer getChapsort() {
        return chapsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.chapsort
     *
     * @param chapsort the value for tb_catalog.chapsort
     *
     * @mbggenerated
     */
    public void setChapsort(Integer chapsort) {
        this.chapsort = chapsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.nodesort
     *
     * @return the value of tb_catalog.nodesort
     *
     * @mbggenerated
     */
    public Integer getNodesort() {
        return nodesort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.nodesort
     *
     * @param nodesort the value for tb_catalog.nodesort
     *
     * @mbggenerated
     */
    public void setNodesort(Integer nodesort) {
        this.nodesort = nodesort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.sliceflag
     *
     * @return the value of tb_catalog.sliceflag
     *
     * @mbggenerated
     */
    public Integer getSliceflag() {
        return sliceflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.sliceflag
     *
     * @param sliceflag the value for tb_catalog.sliceflag
     *
     * @mbggenerated
     */
    public void setSliceflag(Integer sliceflag) {
        this.sliceflag = sliceflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_catalog.idcode
     *
     * @return the value of tb_catalog.idcode
     *
     * @mbggenerated
     */
    public String getIdcode() {
        return idcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_catalog.idcode
     *
     * @param idcode the value for tb_catalog.idcode
     *
     * @mbggenerated
     */
    public void setIdcode(String idcode) {
        this.idcode = idcode == null ? null : idcode.trim();
    }
}