package com.hongtu.slice.db.entity;

public class TbSlice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_slice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_slice.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_slice.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_slice.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_slice.visible
     *
     * @mbggenerated
     */
    private Byte visible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_slice.sortid
     *
     * @mbggenerated
     */
    private Integer sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_slice.tourist
     *
     * @mbggenerated
     */
    private Integer tourist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_slice.id
     *
     * @return the value of tb_slice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_slice.id
     *
     * @param id the value for tb_slice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_slice.name
     *
     * @return the value of tb_slice.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_slice.name
     *
     * @param name the value for tb_slice.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_slice.path
     *
     * @return the value of tb_slice.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_slice.path
     *
     * @param path the value for tb_slice.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_slice.pid
     *
     * @return the value of tb_slice.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_slice.pid
     *
     * @param pid the value for tb_slice.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_slice.visible
     *
     * @return the value of tb_slice.visible
     *
     * @mbggenerated
     */
    public Byte getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_slice.visible
     *
     * @param visible the value for tb_slice.visible
     *
     * @mbggenerated
     */
    public void setVisible(Byte visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_slice.sortid
     *
     * @return the value of tb_slice.sortid
     *
     * @mbggenerated
     */
    public Integer getSortid() {
        return sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_slice.sortid
     *
     * @param sortid the value for tb_slice.sortid
     *
     * @mbggenerated
     */
    public void setSortid(Integer sortid) {
        this.sortid = sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_slice.tourist
     *
     * @return the value of tb_slice.tourist
     *
     * @mbggenerated
     */
    public Integer getTourist() {
        return tourist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_slice.tourist
     *
     * @param tourist the value for tb_slice.tourist
     *
     * @mbggenerated
     */
    public void setTourist(Integer tourist) {
        this.tourist = tourist;
    }
}